Add section on includeLevel to readme
static-dev/spike-contentful pull request #101
Opened 2018-08-03 14:37 UTC by martin3walker

Include a section about how to return links more than one level deep. Useful because Contentful advocates for structuring content in a way the makes use of many references ([see article](https://www.contentful.com/r/knowledgebase/topics-and-assemblies/)). So, this seems like a problem many people could run into if they're reading Contentful's docs.

2018-08-03 20:35 UTC, jescalan requested changes
This is fantastic, thank you for the contribution! Just one small adjustment I noticed and we can get this merged.

2018-08-03 20:35 UTC, jescalan commented on README.md
> +Spike's default settings return only the first level of links, meaning that returning __Content Entry A__ from above will also retun __Content Entry B__, but not __Content Entry C__. There is an opti
So this is not specific to spike, it is actually contentful's default, which we do not change out of respect for the choices they made with their client. I think it might make it more accurate if it was changed to "Contentful's default settings..."

2018-08-06 14:59 UTC, jescalan commented
👌 looks great - thanks again for contributing!

2018-08-06 14:59 UTC, merged

2018-08-06 15:26 UTC, martin3walker commented
Thanks for a great static site generator!